blank_issues_enabled: false
contact_links:
  - name: Bug Report Guidelines
    url: https://github.com/yoonmoonsick/dnd2024?tab=readme-ov-file#bug-report-guidelines
    about: Please read the bug report guidelines before submitting an issue.
